<?php 
	$this->headScript()->appendFile('/resources/tiny_mce/tiny_mce.js')
					   ->appendFile('/js/common/newsEditor.js');
	$display = 'none';
?>
<script>
	var divReplayId;
	
	function postComment(){
		document.forms["commentForm"].submit();
	}

	function checkDivReplayId(value){
		divReplayId = document.getElementById('divReplayId');
		if(value != 0){
			divReplayId.style.display = 'block';
		}
		else{
			divReplayId.style.display = 'none';
		}
	}
</script>
<h1 class="header">
	Write News
</h1>
<div class="divLeft">
	<!-- 
	<div class="RoundBlack"> 
		<div style="padding:10px 20px 20px 20px;">
			<center><div style="font-size:22px;">ข้อแนะนำการเขียนข่าว</div></center>
			เนื้อหาของข่าว
			<ul class="circle">
				<li style="margin-left:25px;">ต้องเกี่ยวกับ DotA ในแวดวงการแข่งขัน</li>
				<li style="margin-left:25px;">technique การเล่นที่ยอดเยี่ยม และแปลกใหม่</li>
				<li style="margin-left:25px;">การลงรูป จะลงได้รูปเดียว ( ไม่นับรูป icon hero และ item ที่เว็บเรามีให้ลงใน editer ) ซึ่งรูปจะอยู่ที่ด้านซ้ายของข่าว  แสดงผลบนเว็บด้วยขนาด 150x150 pixel</li>
				<li style="margin-left:25px;">ห้ามเขียนข่าว "ด่า" หรืออะไรก็ตามที่เป็นชนวนให้เกิด ดราม่า</li>
				<li style="margin-left:25px;">ใช้ [--break--] ขั้น ถ้าต้องการให้เนื้อหาที่หน้าแรกหยุดแค่ตรงนั้น เช่น aaa [--break--] bbb หน้าแรกจะเห็นแค่ aaa แต่กดเข้าไปอ่านข่าวด้านใน จะเห็น aaa bbb</li>
			</ul>
			ข้อตกลง ต่างๆ
			<ul class="circle">
				<li style="margin-left:25px;">ข่าวของท่านจะยังไม่ถูกนำขึ้นเว็บทันที ที่ท่านกดปุ่ม post จะต้องผ่านการตรวจสอบจาก webmaster ก่อนว่าข่าวนั้น ตรงตามเงื่อนไข ถึงจะ online ได้</li>
				<li style="margin-left:25px;">ทางเราขอสงวนสิทธิ์ในการ แก้ไขข้อความบางส่วน ก่อนนำขึ้นเว็บ โดยไม่แจ้งให้ทราบล่วงหน้า</li>
				<li style="margin-left:25px;">ทางเราขอสงวนสิทธิ์ในการ ไม่ให้หัวข้อขึ้นเว็บ โดยไม่แจ้งสาเหตุ</li>
			</ul>
		</div>
	</div>
	-->
	<div class="divPostComment">
		<form method="post" id="commentForm" action="/index/processnews">
			<input type="hidden" id="mode" name="mode" value="addNews"></input>
			<div class = "headPostComment">
				Post News
			</div>
			<div class = "bodyPostComment">
				<div style="margin: 5px 5px 5px 5px;">
					<div style="margin: 10px 0px 10px 5px;">หัวข้อข่าว: <input type="text" id="topic" name="topic" size="100"></input></div>
					<div style="margin: 10px 0px 10px 5px;">หัวข้อข่าว EN: <input type="text" id="topicEN" name="topicEN" size="100"></input></div>
					<div style="margin: 10px 0px 10px 5px;">Url Image: <input type="text" id="imageName" name="imageName" size="100"></input></div>
					<div style="margin: 10px 0px 10px 5px;">Credit: <input type="text" id="creditName" name="creditName" size="100"></input></div>
					<div style="margin: 10px 0px 10px 5px;">Credit Link: <input type="text" id="creditLink" name="creditLink" size="100"></input></div>
                    <div style="margin: 10px 0px 10px 5px;">Tags: <input type="text" id="tags" name="tags" size="100"></input></div>
					<div style="margin: 10px 0px 10px 5px;">
						Replay Type :
						<input type="radio" name="replayType" value="0" onchange="checkDivReplayId('0');" checked /><span style="margin:0px 5px;">Not Replay</span>
						<input type="radio" name="replayType" value="1" onchange="checkDivReplayId('1');"/><span style="margin:0px 5px;">Replay แนะนำ</span>
						<input type="radio" name="replayType" value="2" onchange="checkDivReplayId('2');"/><span style="margin:0px 5px;">Replay Analysis</span>
					</div>
					<div style="margin: 10px 0px 10px 5px;display:<?php echo $display;?>;" id="divReplayId">
						Replay Id : <input type="text" id="replayId" name="replayId" />
					</div>
					<div style="margin: 10px 0px 10px 5px;text-align:center;">
						<input type="button" id="btPost" class="submitBtn" name="btPost" value="Post" onclick="postComment();"></input>
					</div>
					<center>
						ไทย <br />
						<textarea cols="100" rows="30" id="comment" name="comment" class="mceEditor" style="visibility: hidden;"></textarea>
						<br/>
						Eng <br />
						<textarea cols="100" rows="30" id="commentEN" name="commentEN" class="mceEditor" style="visibility: hidden;"></textarea>
					</center>
					<div style="margin: 10px 0px 10px 5px;">
						<font color="black">Team:</font><br/> 
						<?php foreach ($this->tagTeam as $team): ?>
                        <input type="checkbox" id="tag<?php echo $team->id;?>" name="tag<?php echo $team->id;?>" style="margin:5px;" disabled="disabled">
								<?php echo $team->tagName;?>
							</input>
						<?php endforeach ?>
						<br/><font color="black">Player</font><br/>
						<?php foreach ($this->tagPlayer as $player): ?>
							<input type="checkbox" id="tag<?php echo $player->id;?>" name="tag<?php echo $player->id;?>" style="margin:5px;" disabled="disabled">
								<?php echo $player->tagName;?>
							</input>
						<?php endforeach ?>
						<br/><font color="black">Other</font><br/>
						<?php foreach ($this->tagOther as $other): ?>
							<input type="checkbox" id="tag<?php echo $other->id;?>" name="tag<?php echo $other->id;?>" style="margin:5px;" disabled="disabled">
								<?php echo $other->tagName;?>
							</input>
						<?php endforeach ?>
					</div>
				</div>
				<div align="center" style="margin:10px 0px 10px 0px;">
					<input type="button" id="btPreview" class="submitBtn" name="btPreview" value="Preview" onclick="tinyMCE.activeEditor.execCommand('mcePreview');"></input>
					<input type="button" id="btPost" class="submitBtn" name="btPost" value="Post" onclick="postComment();"></input>
				</div>
			</div>
		</form>
	</div>
</div>