<? $this->headScript()->appendFile('/js/replay/replayView.js');?>
<script>
	document.title = "<?php echo addslashes($this->replayPageTitle); ?>";
	replayRate = '<?=$this->replayRate;?>';
</script>
<?php 
	$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
	$this->headMeta()->setProperty('og:title', addslashes($this->replayTitle))
				 	 ->setProperty('og:description', $this->description);
?>
<h1 class="header">
	DotA Replay
</h1>
<div class="divLeft">
	<?php if (Zend_Auth::getInstance()->hasIdentity() && Eaglet_Utils_Auth::isAdmin()):?>
		<div class="manageReplay">
			<input id="editReplayBtn" class="submitBtn" type="button" value="Edit Replay" onclick="editReplay();" />
			<input class="submitBtn" type="button" value="Delete Replay" onclick="confirmDeleteReplay('<?=$this->url(array('controller'=>'replay','action'=>'delete'))?>');" />
		</div>
		<div id="editReplayDiv" class="replayContent editReplayDiv">
			<form method="post">
				<table class="uploadReplayForm">
					<tbody>
						<tr>
							<td style="padding-right: 10px;"><span class="label">การแข่งขันรายการ</span></td>
							<td>
								<span class="label">: </span>
								<input type="text" name="matchContest" id="matchContest" value="<?=$this->matchContest;?>" />
							</td>
						</tr>
						<tr>
							<td><span class="label">ชื่อ Sentinel ทีม</span><span class="mandatory"> *</span></td>
							<td>
								<span class="label">: </span>
								<input type="text" name="sentinelTeamName" id="sentinelTeamName" value="<?=$this->sentinelTeam;?>" />
							</td>
						</tr>
						<tr>
							<td><span class="label">ชื่อ Scourge ทีม</span><span class="mandatory"> *</span></td>
							<td>
								<span class="label">: </span>
								<input type="text" name="scourgeTeamName" id="scourgeTeamName" value="<?=$this->scourgeTeam;?>" />
							</td>
						</tr>
						<tr>
							<td><span class="label">ทีมชนะ</span></td>
							<td><span class="label">: </span>
								<select name="replay_winner" id="replay_winner">
									<option value="Automatic">Unknown</option>
									<option value="Sentinel">Sentinel</option>
									<option value="Scourge">Scourge</option>
								</select>
							</td>
						</tr>
						<tr>
							<td><span class="label">ระดับความมัน</span></td>
							<td><span class="label">: </span>
								<select name="rate" id="rate">
									<option value="0">ธรรมดา</option>
									<option value="1">มันมาก</option>
									<option value="2">มันสัดสัด</option>
								</select>
							</td>
						</tr>
						<tr>
							<td class="replayDescription"><span class="label">รายละเอียด</span></td>
							<td>
								<span class="replayDescription label">: </span>
								<textarea name="replay_text" id="replay_text" cols="65" rows="4"></textarea>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="replaySaveBtn"><input class="submitBtn" type="submit" value="Save" name="saveEditReplay" /></div>
			</form>
		</div>
	<?php endif;?>
	<div class="wrapper">
		<div class="replay">
		<?php
		  $colors = array();
		  $names = array();
		  
		  if (file_exists($this->replayDir.$this->replayFile.'.txt')) {
		        $txt_file = fopen($this->replayDir.$this->replayFile.'.txt', 'r');
		        
		        $data = "";
		        while( ($buff = fgets($txt_file)) != null) {
		            $data .= $buff;    
		        }
		        
		        $replay = unserialize($data);
		        fclose($txt_file);    
		  } else if (isset($this->replayFile)) {
		        $replay = new replay($this->replayDir.$this->replayFile);
		        
		        $txt_file = fopen($this->replayDir.$this->replayFile.'.txt', 'a');
		        flock($txt_file, 2);
		        fputs($txt_file, serialize($replay));
		        flock($txt_file, 3);
		        fclose($txt_file);
		  } else {
		        exit('No replay file given.');
		        $error = 1;
		  }
		  
		  $version = sprintf('%02d', $replay->header['major_v']);
		  
		  echo "<h2 class='replay_h2'>".$this->replayTitle."</h2>";
		  
		  echo ('<div class="replayDetailContent" style="width: 293px; float: left;">
		        <span class="label">Host: </span> '.(isset($replay->game['creator']) ? $replay->game['creator'] : "N/A").' 
		    </div>
		    <div class="replayDetailContent" style="width: 293px; float: right;">
		    	<span class="label">Saver: </span> '.(isset($replay->game['saver_name']) ? $replay->game['saver_name'] : "N/A").' 
		    </div>
		    <br />
		    <div class="replayDetailContent" style="width: 293px; float: left;">
		        <span class="label">Players: </span> '.(isset($replay->game['player_count']) ? $replay->game['player_count'] : "N/A").'
		    </div>
		    <div class="replayDetailContent" style="width: 293px; float: right;">
		        <span class="label">Version: </span> 1.'.$version.'
		    </div>
		    <br />    
		    <div class="replayDetailContent" style="width: 293px; float: left;">
		        <span class="label">Length: </span> '.convert_time($replay->header['length']).'
		    </div>
		    <div class="replayDetailContent" style="width: 293px; float: right;">
		        <span class="label">Observers: </span> '.$replay->game['observers'].'
		    </div>
		    <div class="replayDetailContent" style="width: 293px; float: left;">
		    <span class="label">View: </span> '.$this->totalView.'
		    </div>
		    <div class="replayDetailContent" style="width: 293px; float: right;">
		    <span class="label">Download: </span> '.$this->totalDownload.'
		    </div>');
			if(Zend_Auth::getInstance()->hasIdentity() && Zend_Auth::getInstance()->getStorage()->read()->rankId == 1) {
		  		echo ('<div class="replayDetailContent" style="width: 590px;">
				        <span class="label">ReplayId </span> '.$this->replayId.'
				    </div>');
			}
		  echo ('<div class="replayDetailContent" style="width: 590px;">
		        <span class="label">Map: </span> '.$replay->game['map'].'
		    </div>
		    <div class="replayDetailContent winnerSpoil" style="width: 590px;">
                <span class="label">Winner: </span>
                <a class="reveal">Show</a>
                <span class="spoiler">'.$replay->extra['winner'].'</span>
            </div>
            <div class="clear"></div>
		    <div class="replayDetailContent" style="width: 590px;">
			    <span class="label">Download: </span> <a class="replayLink" href="'.$this->url(array(
			    													"controller"=>"replay",
			    													"action"=>"download",
			    													"f"=>$this->replayFile,
			    													"fc"=>$replay->extra['original_filename']))
		  							.'">'.$replay->extra['original_filename'].'</a>
		    </div>');
		   echo ('
		    <div style="display: '.($replay->bans_num > 0 ? 'block' : 'none').'" >
		    <hr class="viewReplay" />
		    <h2 class="replay_h2"> Draft Heroes </h2>
		    <div class="replayDetailContent">');

    $firstTeamBans = array('', '');
    $secondTeamBans = array('', '');
    $firstTeamPicks = array('', '', '');
    $secondTeamPicks = array('', '', '');

    $firstBanAmount = 3;

    $heroImageTemplate = '<img src="${image}" title="${name}" alt="${name}" class="draftHero">';
    $isSentinelFirstDraft = false;
    
    $isMapBanTwiceRule = false;
    if (isset($replay->game['dota_major']) &&
            isset($replay->game['dota_minor']) &&
            (($replay->game['dota_major'] == 6 && $replay->game['dota_minor'] >= 68) || $replay->game['dota_major'] > 6)) {
        $isMapBanTwiceRule = true;
    }

    foreach ($replay->bans as $index => $hero) {
        if ($index == 0 && $hero->extra == 0) {
            $isSentinelFirstDraft = true;
        }
        $imageHtml = '';
        if (method_exists($hero, 'getArt')) {
            $imageHtml = str_replace('${image}', $hero->getArt(), $heroImageTemplate);
            $imageHtml = str_replace('${name}', $hero->getName(), $imageHtml);
        }
        if ($index % 2 == 0) {
            if ($index < $firstBanAmount * 2) {
                $firstTeamBans[0] .= $imageHtml;
            } else {
                $firstTeamBans[1] .= $imageHtml;
            }
        } else {
            if ($index < $firstBanAmount * 2) {
                $secondTeamBans[0] .= $imageHtml;
            } else {
                $secondTeamBans[1] .= $imageHtml;
            }
        }
    }
    
    if (!$isMapBanTwiceRule) {
        $firstTeamBans[0] .= $firstTeamBans[1];
        $secondTeamBans[0] .= $secondTeamBans[1];
    }
        
    foreach ($replay->picks as $index => $hero) {
        $imageHtml = str_replace('${image}', $hero->getArt(), $heroImageTemplate);
        $imageHtml = str_replace('${name}', $hero->getName(), $imageHtml);

        // Output for CM Mode post 6.68 (3/2 ban split)
        if ($isMapBanTwiceRule) {
            if ($index == 0) {
                $firstTeamPicks[0] .= $imageHtml;
            } else if ($index == 3 || $index == 4) {
                $firstTeamPicks[1] .= $imageHtml;
            } else if ($index == 6 || $index == 8) {
                $firstTeamPicks[2] .= $imageHtml;
            } else if ($index == 1 || $index == 2) {
                $secondTeamPicks[0] .= $imageHtml;
            } else if ($index == 5) {
                $secondTeamPicks[1] .= $imageHtml;
            } else if ($index == 7 || $index == 9) {
                $secondTeamPicks[2] .= $imageHtml;
            }
        } else { // Output for pre 6.68 CM Mode
            if ($index == 0) {
                $firstTeamPicks[0] .= $imageHtml;
            } else if ($index == 3 || $index == 4) {
                $firstTeamPicks[1] .= $imageHtml;
            } else if ($index == 7 || $index == 8) {
                $firstTeamPicks[2] .= $imageHtml;
            } else if ($index == 1 || $index == 2) {
                $secondTeamPicks[0] .= $imageHtml;
            } else if ($index == 5 || $index == 6) {
                $secondTeamPicks[1] .= $imageHtml;
            } else if ($index == 9) {
                $secondTeamPicks[2] .= $imageHtml;
            }
        }
    }

    $sentinelBans = null;
    $scourgeBans = null;
    $sentinelPicks = null;
    $scourgePicks = null;
    if ($isSentinelFirstDraft) {
        $sentinelBans = array($firstTeamBans[0], $firstTeamBans[1]);
        $scourgeBans = array($secondTeamBans[0], $secondTeamBans[1]);
        $sentinelPicks = array($firstTeamPicks[0], $firstTeamPicks[1], $firstTeamPicks[2]);
        $scourgePicks = array($secondTeamPicks[0], $secondTeamPicks[1], $secondTeamPicks[2]);
    } else {
        $sentinelBans = array($secondTeamBans[0], $secondTeamBans[1]);
        $scourgeBans = array($firstTeamBans[0], $firstTeamBans[1]);
        $sentinelPicks = array($secondTeamPicks[0], $secondTeamPicks[1], $secondTeamPicks[2]);
        $scourgePicks = array($firstTeamPicks[0], $firstTeamPicks[1], $firstTeamPicks[2]);
    }
           
        echo
        '<table class="draftHeroTable">
            <tr>
                <td class="draftHeroTableHeader draftTeamName">
                    ' . $this->sentinelTeam . '
                </td>
                <td class="draftHeroTableHeader draftTeamName">
                    ' . $this->scourgeTeam . '
                </td>
            </tr>
            <tr>
                <td class="draftHeroTableHeader" colspan="2" style="text-align:center;">
                    <b>‎Ban</b>
                </td>
            </tr>
            <tr>
                <td class="draftHeroTableData">' . $sentinelBans[0] . '</td>
                <td class="draftHeroTableData">' . $scourgeBans[0] . '</td>
            </tr>';
        if ($isMapBanTwiceRule) {
            echo 
            '<tr>
                <td class="draftHeroTableData">' . $sentinelBans[1] . '</td>
                <td class="draftHeroTableData">' . $scourgeBans[1] . '</td>
            </tr>';
        }
            echo
            '<tr>
                <td class="draftHeroTableHeader" colspan="2" style="text-align:center;">
                    <b>Pick</b>
                </td>
            </tr>
            <tr>
                <td class="draftHeroTableData">' . $sentinelPicks[0] . '</td>
                <td class="draftHeroTableData">' . $scourgePicks[0] . '</td>
            </tr>
            <tr>
                <td class="draftHeroTableData">' . $sentinelPicks[1] . '</td>
                <td class="draftHeroTableData">' . $scourgePicks[1]. '</td>
            </tr>
            <tr>
                <td class="draftHeroTableData">'. $sentinelPicks[2] . '</td>
                <td class="draftHeroTableData">' . $scourgePicks[2] . '</td>
            </tr>
        </table>';
            
		   echo '</div>';
        ?>
        	</div>
        </div>
    </div>
    <div class="manageScoreboard">
    	<img id="loadingIcon" alt="loading" src="/images/web/loading_icon.gif" />
		<input id="viewScoreBoardBtn" type="button" value="<?=$this->translate('REPLAY_VIEWSCORE');?>" class="greenBtn" style="visibility: hidden;" />
	</div>
    <div id="scoreBoard" class="wrapper">
        <div class="replay">
        <?php 
		   // Display Teams 
		   for($i = 0; $i < 2; $i++) {
		       $team = ( $i == 0 ? "Sentinel" : "Scourge" );
		       
		       echo '
		            <hr class="viewReplay" />
		            <h2 class="replay_h2"> '.$team.' </h2>
		            <div class="replayContent" style="width: 600px; padding-left: 0px; margin-left: 0px;">
		                <table class="statsTable" border="0" cellpadding="0" cellspacing="0" width="100%">
		                <tr class="tableHeader">
		                    <td class="tableHeader" width="180px">Name </td>
		                    <td class="tableHeader">Level </td>
		                    <td class="tableHeader">APM </td>
		                    <td class="tableHeader">K/D/A </td>
		                    <td class="tableHeader">CS </td>
		                    <td class="tableHeader">Extra </td>   
		                </tr>';
		       
		       foreach($replay->teams[$i] as $pid=>$player) {
		             
		             // Convert 1.2 version to legacy (1.1) output
		             if ( isset($replay->ActivatedHeroes) ) {
		                 if ( $replay->stats[$player['dota_id']]->getHero() == false ) continue;
		                                   
		                 $t_heroName = $replay->stats[$player['dota_id']]->getHero()->getName();
		                 
		                 // Set level
		                 $player['heroes'][$t_heroName]['level'] = $replay->stats[$player['dota_id']]->getHero()->getLevel();
		                 
		                 $t_heroSkills = $replay->stats[$player['dota_id']]->getHero()->getSkills();
		                 
		                 // Convert skill array to old format
		                 foreach ( $t_heroSkills as $time => $skill ) {
		                     $player['heroes'][$t_heroName]['abilities'][$time] = $skill;
		                 }
		                 
		                 $player['heroes'][$t_heroName]['data'] = $replay->stats[$player['dota_id']]->getHero()->getData();
		             }
		           
		             // Get player's hero
		             foreach($player['heroes'] as $name=>$hero) {
		                 
		                if( $name == "order" || !isset($hero['level'])) continue; 
		                
		                
		                 
		                if( $name != "Common" ) {    
		                    // Merge common skills and atribute stats with Hero's skills
		                    if(isset($player['heroes']['Common']) ) {
		                        
		                        $hero['level'] += $player['heroes']['Common']['level'];
		                        $hero['abilities'] = array_merge($hero['abilities'], $player['heroes']['Common']['abilities']);
		                    }
		                    if ( $hero['level'] > 25 ) {
		                        $hero['level'] = 25;    
		                    }
		                    @ksort($hero['abilities']);
		                    $p_hero = $hero;
		                
		                    break;    
		                }
		             }
		             
		             echo ('<tr class="table'.$team.'" onclick="javascript:toggleDisplayRow(\'player'.$player['player_id'].'\');">
		                <td class="table'.$team.' playerName">');
		             echo '<img src="'.$p_hero['data']->getArt().'" width="25px" height="25px"';
		             echo ' alt="'.$p_hero['data']->getName().'" title="'.$p_hero['data']->getName().'"';
		             echo (' style="vertical-align: middle;"/> <span class="playerName" style="font-weight: bolder;">'.$player['name'].' </span></td>
		                <td class="table'.$team.'">'.$p_hero['level'].' </td>
		                <td class="table'.$team.'">'.round( (60 * 1000 * $player['apm']) / ($player['time'])).' </td>');
		             
		             
		             if(isset($replay->stats[$player['dota_id']])) {
		                $stats = $replay->stats[$player['dota_id']];
		                echo ('<td class="table'.$team.'">'.(isset($stats->HeroKills) ? $stats->HeroKills : 0).'/'.(isset($stats->Deaths) ? $stats->Deaths : 0).'/'.(isset($stats->Assists) ? $stats->Assists : 0).' </td>
		                    <td class="table'.$team.'">'.(isset($stats->CreepKills) ? $stats->CreepKills : 0).'/'.(isset($stats->CreepDenies) ? $stats->CreepDenies : 0).'/'.(isset($stats->Neutrals) ? $stats->Neutrals : 0).' </td>');
		                    
		             }
		             else {
		                 echo ('<td class="table'.$team.'"> N/A </td>
		                    <td class="table'.$team.'"> N/A </td>' );
		                                                
		             }
		             echo ('<td class="table'.$team.'"><a class="replayLink" onmouseover="javascript:toggleRowLink(false);" onmouseout="javascript:toggleRowLink(true);" href="javascript:toggleDisplay(\'player'.$player['player_id'].'\');"><div id="ih_player'.$player['player_id'].'">Detail</div></a></td>    
		                </tr>');
		            
		            // Start extra info display
		            echo ('<tr class="tableExtra">
		                    <td colspan="6" class="tableExtra">
		                        <div width="100%" style="display: none;" id="player'.$player['player_id'].'" >');
		           
		           
		            // Display Inventory
		            echo  '<div class="inventory" style="float: left;">';
		            for($j = 0; $j < 6; $j++) {
		                $art = ( isset($stats->Inventory[$j]) && is_object($stats->Inventory[$j]) ) ?  $stats->Inventory[$j]->getArt() : "/resources/replay-parser/images/BTNEmpty.gif";
		                $name = ( isset($stats->Inventory[$j]) && is_object($stats->Inventory[$j]) ) ?  $stats->Inventory[$j]->getName() : "Empty"; 
		                
		                
		                echo '<img src="'.$art.'" width="48px" height="48px" alt="'.$name.'" title="'.$name.'" />';
		            }
		            echo '</div>';
		            
		            // Handle player left events
		            if(isset($player['time'])) {
		                $playerLeaveTime = convert_time($player['time']);
		            }
		            else {
		                $playerLeaveTime = convert_time($replay->header['length']);
		            }
		            if(isset($player['leave_result'])) {
		                $leaveResult = $player['leave_result'];
		            }
		            else {
		                $leaveResult = "Finished";
		            }
		            
		            // Display other
		            echo  ('<div class="extraOther" style="float: right;">
		                        <div class="displaySelect">
		                            Left at '.$playerLeaveTime.', reason: '.$leaveResult.'.');
		            if(isset($replay->stats[$player['dota_id']]->AA_Total) && isset($replay->stats[$player['dota_id']]->AA_Hits) && $replay->stats[$player['dota_id']]->AA_Total > 0 ) {
		                echo ("<br />Arrow accuracy: ".round((($replay->stats[$player['dota_id']]->AA_Hits / $replay->stats[$player['dota_id']]->AA_Total)*100))."% 
		                        (".$replay->stats[$player['dota_id']]->AA_Hits."/".$replay->stats[$player['dota_id']]->AA_Total.")");
		            }
		            if(isset($replay->stats[$player['dota_id']]->HA_Total) && isset($replay->stats[$player['dota_id']]->HA_Hits) && $replay->stats[$player['dota_id']]->HA_Total > 0 ) {
		                echo ("<br />Hook accuracy: ".round((($replay->stats[$player['dota_id']]->HA_Hits / $replay->stats[$player['dota_id']]->HA_Total)*100))."% 
		                        (".$replay->stats[$player['dota_id']]->HA_Hits."/".$replay->stats[$player['dota_id']]->HA_Total.")");
		            }
		                                
		           echo    ('         </div>
		                        <div class="displaySelect">
		                            <a class="replayLink" href="javascript:toggleDisplayedExtra(\'player'.$player['player_id'].'_skills\',\''.$player['player_id'].'\');">Skills</a> | 
		                            <a class="replayLink" href="javascript:toggleDisplayedExtra(\'player'.$player['player_id'].'_items\',\''.$player['player_id'].'\');">Items</a> |
		                            <a class="replayLink" href="javascript:toggleDisplayedExtra(\'player'.$player['player_id'].'_actions\',\''.$player['player_id'].'\');">Actions</a>
		                        </div>');
		            
		            // Display skills
		            echo '<div id="player'.$player['player_id'].'_skills" class="extraInfo" >';
		            
		            $i_skill = 0;
		            unset($a_level);
		            foreach ($p_hero['abilities'] as $time=>$ability) {
		                $i_skill++;
		                if ($i_skill > 25 ) break;
		                  
		                if(!isset($a_level[$ability->getName()])) {
		                      $a_level[$ability->getName()] = 1;
		                  }
		                  else {
		                      $a_level[$ability->getName()]++;
		                  }
		                  echo ('<b>'.($i_skill < 10 ? "&nbsp;&nbsp;" : "").$i_skill.' </b><img style="vertical-align: middle;" src="'.$ability->getArt().'" width="18px" height="18px" /> &#160;<b>'.convert_time($time).'</b>&#160; '.$ability->getName().' '.$a_level[$ability->getName()].'<br />');
		            }
		            echo '</div>';
		            
		            
		            // Display items
		            echo '<div id="player'.$player['player_id'].'_items" class="extraInfo" style="display: none;">';
		            
		            foreach ($player['items'] as $time=>$item) {
		                if (is_object($item) && $item->getName() != "Select Hero" ) {
		                  echo ('<img style="vertical-align: middle;" src="'.$item->getArt().'" alt="Item" title="'.$item->getName().'" width="18px" height="18px" /> &#160;<b>'.$time.'</b>&#160; '.$item->getName().'<br />');
		                }
		            }
		            echo '</div>';
		            
		            // Display actions
		            echo '<div id="player'.$player['player_id'].'_actions" class="extraInfo" style="display: none;">';
		            
		            if (isset($player['actions_details'])) {
		                  ksort($player['actions_details']);
		                  
		                  $px_per_action = 400 / $player['apm'];
		                  
		                  foreach ($player['actions_details'] as $name=>$info) {
		                    echo ('<b>'.$name.' '.$info.'</b><div class="graph" style="width: '.round($info * $px_per_action).'px;"></div><br />');
		                  }
		            }
		            echo '</div>'; 
		           
		           
		           echo '</div>';
		           // End extra info display
		           echo   ('</div>
		                     </td>
		                    </tr>');
		            
		            
		            // Remember colors for Chat display.
		            if ($player['color']) {
		                $colors[$player['player_id']] = $player['color'];
		                $names[$player['player_id']] = $player['name'];
		            }    
		       }
		       echo "</table></div>";
		   }
		    
		   /* Display Description */
		   if ($replay->extra['text']) {
			    echo '<hr class="viewReplay" />
			    <h2 class="replay_h2"> Description </h2>
			    <div class="replayDetailContent">
			       <textarea id="replayDesc" class="replayDetail" disabled="disabled">'.$replay->extra['text'].'</textarea>
			    </div>';
		   }
		   echo $this->inlineScript()->appendScript("winner = '" . $replay->extra['winner'] . "';");
		   /* Display Chat */ 
		   echo '<hr class="viewReplay" />
		    <h2 class="replay_h2"> Chat Log </h2>
		    <div class="chatWindow">';
		    
		   
		   foreach ($replay->chat as $content) {
		        $prev_time = $content['time'];
		        
		        echo('('.convert_time($content['time']));
		        
		        if (isset($content['mode']) && isset($colors[$content['mode']]) && isset($names[$content['mode']])) {
		          if (is_int($content['mode'])) {
		            echo(' / '.($content['mode'] == 0x01 ? "Allied" : ""));
		          }
		          else {
		            echo(' / '.$content['mode']);
		          }
		        }
		        
		        echo(') ');
		        
		        if (isset($content['player_id'])) {
		          // no color for observers
		          if (isset($colors[$content['player_id']])) {
		            echo('<span style="font-weight: bold;" class="'.$colors[$content['player_id']].'">'.$content['player_name'].'</span>: ');
		          } 
		          else {
		            echo('<span style="font-weight: bold;" class class="observer">'.$content['player_name'].'</span>: ');
		          }
		        }
		
		        echo(htmlspecialchars($content['text'], ENT_COMPAT, 'UTF-8').'<br />');
		  }
		  
		  echo '</div>';  
		?>
		</div>
		<div style="margin: 10px 0px 10px 0px;float:left;">
			<a href="http://twitter.com/share" class="twitter-share-button" data-text="@lendotacom" data-count="horizontal" data-via="XCiNg_Pawanwit">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
		</div>
		<div style="margin: 10px 0px 10px 0px;float:left;">
			<!-- Place this tag in your head or just before your close body tag -->
			<script type="text/javascript" src="https://apis.google.com/js/plusone.js">
			  {lang: 'th'}
			</script>
			
			<!-- Place this tag where you want the +1 button to render -->
			<g:plusone></g:plusone>
		</div>
		<div style="margin: 10px 0px 10px 0px;float:left;width:350px;">
			<div id="fb-root"></div><fb:like href="http://lendota.com/replay/view/file/<?php echo $this->replayFile;?>" send="true" layout="button_count" width="450" show_faces="true" colorscheme="dark"></fb:like>
		</div>
		<div style="clear:both;"></div>
	</div>
	<div class="fbCommentReplay">
		<div class="fb-comments" data-href="http://lendota.com/replay/view/file/<?=$this->replayFile;?>" data-num-posts="10" data-width="650" data-colorscheme="light"></div>
	</div>
</div>