<h1 class="header">
	Create New Tournament
</h1>
<?php include("leftSide.phtml")?>
<div style="float:left;margin:0px 35px 0px 5px;">
	<div class="RoundBlack" style="width: 550px;padding:20px;">
		<form method="POST" id="matchResultForm" enctype="multipart/form-data">
			<table>
				<tr height="30px">
					<td width="100">Tournament Name : </td>
					<td><input type="text" name="name" /></td>
				</tr>
				<tr height="30px" id="ssBlock">
					<td>Picture : </td>
					<td><input type="text" id="picture" name="picture" /></td>
				</tr>
				<tr height="30px">
					<td width="100">Start Date : </td>
					<td><input type="text" name="startDate" />&nbsp;2013-07-09</td>
				</tr>
				<tr height="30px">
					<td width="100">Deadline Date : </td>
					<td><input type="text" name="deadlineDate" />&nbsp;2013-07-09</td>
				</tr>
				<tr height="30px">
					<td width="100">Award : </td>
					<td><textarea name="award"></textarea></td>
				</tr>
				<tr height="30px">
					<td width="100">Game Amount : </td>
					<td>
						<select name="gameAmount">
							<?php for($i=1; $i<=5; $i+=2){?>
						  		<option value="<?=$i?>"><?=$i?></option>
						  	<?php } ?>
						</select>
					</td>
				</tr>
				<tr height="30px">
					<td width="100">Final Game Amount : </td>
					<td>
						<select name="finalGameAmount">
							<?php for($i=1; $i<=5; $i+=2){?>
						  		<option value="<?=$i?>"><?=$i?></option>
						  	<?php } ?>
						</select>
					</td>
				</tr>
				<tr height="30px">
					<td width="100">Type : </td>
					<td>
						<input type="radio" name="type" value="1" checked/>&nbsp;Single Elimenate
						<input type="radio" name="type" value="2" style="margin-left:15px;" />&nbsp;Double Elimenate
					</td>
				</tr>
				<tr height="30px">
					<td width="100">Third Place : </td>
					<td>
                        <input type="checkbox" name="thirdPlace"/>
					</td>
				</tr>
				<tr>
					<td colspan="2"><input type="submit" class="submitBtn" value="submit" style="margin-left:80px;"/></td>
				</tr>
			</table>
		</form>
	</div>
</div>
<div style="clear:both;"></div>