<h1 class="header">
	Create New Tournament
</h1>
<?php include("leftSide.phtml")?>
<div style="float:left;margin:0px 35px 0px 5px;">
	<div class="RoundBlack" style="width: 550px;padding:20px;">
		<form method="POST" id="matchResultForm" enctype="multipart/form-data">
			<input type="hidden" name="tournamentId" value="<?=$this->tournament->tournamentId;?>"/>
			<table>
				<tr height="30px">
					<td width="100">Tournament Name : </td>
					<td><input type="text" name="name" value="<?=$this->tournament->name;?>" /></td>
				</tr>
				<tr height="30px" id="ssBlock">
					<td>Picture : </td>
					<td><input type="text" name="picture" value="<?=$this->tournament->picture;?>" /></td>
				</tr>
				<tr height="30px">
					<td width="100">Start Date : </td>
					<td><input type="text" name="startDate" value="<?=$this->tournament->startDate;?>" />&nbsp;2012-07-09</td>
				</tr>
				<tr height="30px">
					<td width="100">Deadline Date : </td>
					<td><input type="text" name="deadlineDate" value="<?=$this->tournament->deadlineDate;?>" />&nbsp;2012-07-09</td>
				</tr>
				<tr height="30px">
					<td width="100">Award : </td>
					<td><textarea name="award"><?=$this->tournament->award;?></textarea></td>
				</tr>
				<tr height="30px">
					<td width="100">Game Amount : </td>
					<td>
						<select name="gameAmount">
							<?php for($i=1; $i<=5; $i+=2){?>
						  		<option value="<?=$i?>" <?php if($this->tournament->gameAmount == $i){?> selected<?php } ?>><?=$i?></option>
						  	<?php } ?>
						</select>
					</td>
				</tr>
				<tr height="30px">
					<td width="100">Final Game Amount : </td>
					<td>
						<select name="finalGameAmount">
							<?php for($i=1; $i<=5; $i+=2){?>
						  		<option value="<?=$i?>" <?php if($this->tournament->finalGameAmount == $i){?> selected<?php } ?>><?=$i?></option>
						  	<?php } ?>
						</select>
					</td>
				</tr>
				<tr height="30px">
					<td width="100">Type : </td>
					<td>
						<input type="radio" name="type" value="1" <?php if($this->tournament->type == 1){?> checked<?php } ?>/>&nbsp;Single Elimenate
						<input type="radio" name="type" value="2" style="margin-left:15px;" <?php if($this->tournament->type == 2){?> checked<?php } ?>/>&nbsp;Double Elimenate
					</td>
				</tr>
				<tr height="30px">
					<td width="100">Active : </td>
					<td>
						<select name="active">
							<?php for($i=0; $i<=3; $i++){?>
						  		<option value="<?=$i?>" <?php if($this->tournament->active == $i){?> selected<?php } ?>><?=$i?></option>
						  	<?php } ?>
						</select>
						0 = กำลังเปิดรับสมัคร, 1 = ปิดรับสมัครแล้ว แต่ยังไม่สร้างตาราง, 2 = สร้างตารางแล้ว 3 = แข่งจบแล้ว
					</td>
				</tr>
				<tr>
					<td colspan="2"><input type="submit" class="submitBtn" value="submit" style="margin-left:80px;"/></td>
				</tr>
			</table>
		</form>
	</div>
</div>
<div style="clear:both;"></div>