<script>
	document.title = 'วิธีการอัพโหลดรีเพลย์';
</script>
<h1 class="header">
	<?=$this->translate('TOURNAMENT_HOWTO_UPLOAD'); ?>
</h1>
<?php include("leftSide.phtml")?>
<div class="RoundBlack" style="float:left;margin:0px 35px 0px 5px;color:#A7A7A7;width:750px;padding:10px;">
	<ol class="number">
		<li><?=$this->translate('TOURNAMENT_HOWTO_UPLOAD_1'); ?><img src="/images/tournament/uploadreplay_tutorial_1.png" width="700"/></li>
		<li><?=$this->translate('TOURNAMENT_HOWTO_UPLOAD_2'); ?><img src="/images/tournament/uploadreplay_tutorial_2.png" width="700"/></li>
		<li><?=$this->translate('TOURNAMENT_HOWTO_UPLOAD_3'); ?></li>
		<li><?=$this->translate('TOURNAMENT_HOWTO_UPLOAD_4'); ?></li>
	</ol>
</div>
<div style="clear:both;"></div>