<script>
	document.title = 'วิธีดูรีเพลย์ย้อนหลังจากไฟล์ Replay';
</script>
<h1 class="header">
	<?=$this->translate('TOURNAMENT_HOWTO_VIEW_REPLAY'); ?>
</h1>
<?php include("leftSide.phtml")?>
<div class="RoundBlack" style="float:left;margin:0px 35px 0px 5px;color:#A7A7A7;width:750px;padding:10px;" >
	<div><?=$this->translate('TOURNAMENT_HOWTO_VIEW_REPLAY_TOPIC'); ?></div>
	<ol class="number">
		<li><?=$this->translate('TOURNAMENT_HOWTO_VIEW_REPLAY_1'); ?></li>
		<li><?=$this->translate('TOURNAMENT_HOWTO_VIEW_REPLAY_2'); ?></li>
		<li><?=$this->translate('TOURNAMENT_HOWTO_VIEW_REPLAY_3'); ?></li>
		<li><?=$this->translate('TOURNAMENT_HOWTO_VIEW_REPLAY_4'); ?></li>
		<li><?=$this->translate('TOURNAMENT_HOWTO_VIEW_REPLAY_5'); ?></li>
	</ol>
	<div style="text-align:center;margin-top:10px;"><img src="/images/tournament/viewreplay_tutorial_1.jpg" /></div>
	<div style="text-align:center;margin-top:20px;"><img src="/images/tournament/viewreplay_tutorial_2.jpg" /></div>
</div>
<div style="clear:both;"></div>