<script>
	document.title = '<?=$this->translate('TOURNAMENT_RULE_TITLE'); ?>';
</script>
<h1 class="header">
	<?=$this->translate('TOURNAMENT_RULE_HEADER'); ?>
</h1>
<?php include("leftSide.phtml")?>
<div style="float:left;margin:0px 35px 0px 5px;color:#A7A7A7;width:850px;">
	<h2 class="tour_rule_h2"><?=$this->translate('TOURNAMENT_RULE_DETAILS'); ?></h2>
	<ol class="number">
		<li><?=$this->translate('TOURNAMENT_RULE_FORMAT'); ?></li>
		<li><?=$this->translate('TOURNAMENT_RULE_SERVER'); ?></li>
		<li><?=$this->translate('TOURNAMENT_RULE_PLAYER'); ?></li>
		<li><?=$this->translate('TOURNAMENT_RULE_MODE'); ?></li>
	</ol>
	<h2 class="tour_rule_h2"><?=$this->translate('TOURNAMENT_RULE_CONDITIONS'); ?></h2>
	<ol class="number">
		<li><?=$this->translate('TOURNAMENT_RULE_MATCH_BEGIN'); ?></li>
		<li><?=$this->translate('TOURNAMENT_RULE_SIDE'); ?><img src="/images/tournament/rule_tutor_1.png" width="750"/></li>
		<li><?=$this->translate('TOURNAMENT_RULE_CREATE_ROOM'); ?><img src="/images/tournament/rule_tutor_2.png" width="750"/></li>
		<li><?=$this->translate('TOURNAMENT_RULE_PRIVATE_ROOM'); ?></li>
		<li><?=$this->translate('TOURNAMENT_RULE_POSTPOND'); ?></li>
		<li><?=$this->translate('TOURNAMENT_RULE_PLAYER_NAME'); ?></li>
	</ol>
	<h2 class="tour_rule_h2"><?=$this->translate('TOURNAMENT_RULE_RULES'); ?></h2>
	<ol style="margin-left:20px;list-style: none;">
		<li><?=$this->translate('TOURNAMENT_RULE_DISCONNECT'); ?></li>
	</ol>
	<h2 class="tour_rule_h2"><?=$this->translate('TOURNAMENT_FAQ_HOWTO_REPORT_RESULT'); ?></h2>
	<ol class="number">
		<li><?=$this->translate('TOURNAMENT_FAQ_HOWTO_REPORT_1'); ?><img src="/images/tournament/report_tutorial_1.png" /></li>
		<li><?=$this->translate('TOURNAMENT_FAQ_HOWTO_REPORT_2'); ?><img src="/images/tournament/report_tutorial_2.png" width="750"/></li>
		<li><?=$this->translate('TOURNAMENT_FAQ_HOWTO_REPORT_3'); ?></li>
		<li><?=$this->translate('TOURNAMENT_FAQ_HOWTO_REPORT_4'); ?></li>
	</ol>
	<h2 class="tour_rule_h2"><?=$this->translate('TOURNAMENT_RULE_SOFT_RULE'); ?></h2>
	<ol class="number">
		<li><?=$this->translate('TOURNAMENT_RULE_HARM'); ?></li>
		<li><?=$this->translate('TOURNAMENT_RULE_TRASH_TALK'); ?></li>
	</ol>
</div>
<div style="clear:both;"></div>