<div style="width:120px;margin: 20px 0px 20px 20px;float:left;">
	<div>
		<a href="<? echo $this->url(array(
					'controller'=> 'guide', 
					'action'=>'index',
					'default', 
					true)); ?>">
			<div style="padding:0px 0px 5px 30px;">Heroes</div>
			<div style=""><img src="/images/skel.jpg" width="100" height="100" alt="dota" /></div>
		</a>
	</div>
	<div>
		<a href="<? echo $this->url(array(
					'controller'=> 'guide', 
					'action'=>'item',
					'default', 
					true)); ?>">
			<div style="padding:10px 0px 5px 30px;">Item</div>
			<div style="float:left;"><img src="/images/tinker.jpg" width="100" height="100" alt="dota" /></div>
			
		</a>
	</div>
	<div>
		<a href="<? echo $this->url(array(
					'controller'=> 'guide', 
					'action'=>'technic',
					'default', 
					true)); ?>">
			<div style="padding:10px 0px 5px 18px;">Technique</div>
			<div style=""><img src="/images/nvm.jpg" width="100" height="100" alt="dota" /></div>
		</a>
	</div>
	<!-- 
	<div>
		<a href="<? echo $this->url(array(
					'controller'=> 'guide', 
					'action'=>'funteam',
					'default', 
					true)); ?>">
			<div style="padding:10px 0px 5px 10px;">Fun team</div>
			<div style=""><img src="/images/drow.jpg" width="100" height="100" alt="dota" /></div>
		</a>
	</div>
	 -->
</div>