<h1 class="header">
	<?php echo $this->translate('SUPPORT_ADVER_ME_TEXT');?>
</h1>
<center>
<div class="RoundBlack" style="width:750px;">
	<div style="margin: 20px 20px 20px 20px;font-size: 16px;text-align:left;">
		<div class="supportStat">
			<div class="supportStatHeader">
				<?php echo $this->translate('SUPPORT_WHY_WITH_US_HEADER');?>
			</div>
				<?php echo $this->translate('SUPPORT_WHY_WITH_US_CONTENT');?>
			<br />
			<div class="supportStatHeader">
				<?php echo $this->translate('SUPPORT_STAT_HEADER');?>
			</div>
			<?php echo $this->translate('SUPPORT_STAT_CONTENT');?>
			<div class="statImage">
				<img src="/images/adver/lendota-stat-2012.png" title="lendota 2012 stat" />
			</div>
			<table>
				<tr>
					<td>Pageview</td>
					<td align="right" width="120px">18,246,260</td>
				</tr>
				<tr>
					<td>Unique IP</td>
					<td align="right" width="120px">2,270,034</td>
				</tr>
			</table>
			<div class="statMoreDetail">
				<?php echo $this->translate('SUPPORT_STAT_MORE_DETAIL');?>
				<a href="http://www.stats.in.th/?cmd=stats&sid=36545&list=y" target="_blank">stats.in.th</a>
			</div>
			<div class="supportStatHeader" style="font-size: 22px;">
				<?php echo $this->translate('SUPPORT_BENEFIT_TOPIC');?>
			</div>
			<?php echo $this->translate('SUPPORT_BENEFIT_DETAIL');?>
			<br /><br />
			<div class="supportStatHeader" style="font-size: 22px;">
				<?php echo $this->translate('SUPPORT_ADS_DETAIL_HEADER');?>
			</div>
		</div>
		<center>
			<div style="margin:10px auto;"><img src="/images/adver/adv.png" width="700" style="border: 2px solid;" /></div>
			<?php echo $this->translate('SUPPORT_POSITION_BANNER_TEXT');?>
			
			<table border="1" style="width:80%;">
				<tr align="center">
					<td>&nbsp;</td>
					<td><?php echo $this->translate('SUPPORT_POSITION_TEXT');?> 1</td>
					<td><?php echo $this->translate('SUPPORT_POSITION_TEXT');?> 2</td>
					<td><?php echo $this->translate('SUPPORT_POSITION_TEXT');?> 3</td>
					<td><?php echo $this->translate('SUPPORT_POSITION_TEXT');?> 4</td>
				</tr>
				<tr align="center">
					<td>1 <?php echo $this->translate('SUPPORT_WEEK_TEXT');?></td>
					<td>800 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
					<td>-</td>
					<td>-</td>
					<td>-</td>
				</tr>
				<tr align="center">
					<td>1 <?php echo $this->translate('SUPPORT_MONTH_TEXT');?></td>
					<td>3,000 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
					<td>2,000 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
					<td>800 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
					<td>4,000 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
				</tr>
				<tr align="center">
					<td>3 <?php echo $this->translate('SUPPORT_MONTH_TEXT');?></td>
					<td>8,100 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
					<td>5,400 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
					<td>2,100 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
					<td>10,800 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
				</tr>
				<tr align="center">
					<td>6 <?php echo $this->translate('SUPPORT_MONTH_TEXT');?></td>
					<td>15,000 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
					<td>10,000 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
					<td>4,000 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
					<td>20,000 <?php echo $this->translate('SUPPORT_BATH_TEXT');?></td>
				</tr>
			</table>
		</center>
		<br/>
		* <?php echo $this->translate('SUPPORT_UIP_TEXT');?><br/><br/>
		
		* <?php echo $this->translate('SUPPORT_PRICE_TEXT');?><br/><br/>
		
		<div style="font-size:20px;"><?php echo $this->translate('SUPPORT_GUIDE_TEXT');?></div>
		<div style="margin:10px 0px 10px 30px;"><?php echo $this->translate('SUPPORT_SEND_EMAIL_TEXT');?></div>
		<div style="margin:10px 0px 10px 30px;"><?php echo $this->translate('SUPPORT_NAME_TEXT');?></div>
		<ul class="circle">
			<li style="margin-left: 60px;"><?php echo $this->translate('SUPPORT_BANK_TEXT');?></li>
		</ul>
		<div style="margin:10px 0px 10px 30px;"><?php echo $this->translate('SUPPORT_SIZE_TEXT');?></div>
		<div><?php echo $this->translate('SUPPORT_NOTE_TEXT');?></div>
		<ul class="circle">
			<li style="margin-left: 30px;"><?php echo $this->translate('SUPPORT_NOTE_DETAIL1_TEXT');?></li> 
			<li style="margin-left: 30px;"><?php echo $this->translate('SUPPORT_NOTE_DETAIL2_TEXT');?></li> 
		</ul>
	</div>
</div>
</center>