<div class="footer">
	<center>
		<div style="padding: 30px 0px 40px 0px;">
			<hr style="color:#EBEBEB;width:90%;background-color: #CCCCCC;" />
			<div class="footerContent" style="margin:20px 0px;">
				<span style="margin-right:10px;">
					www.lendota.com &copy; 2011 - <?php echo date('Y');?>
					| admin@lendota.com
					| <a href="/support">Support us</a>
				</span>
				<script type="text/javascript" language="javascript1.1" src="http://tracker.stats.in.th/tracker.php?sid=36545"></script><noscript><a target="_blank" href="http://www.stats.in.th/">www.Stats.in.th</a></noscript>
				<span style="float:right;margin:0px 40px 20px 0px;font-size:14px;font-style:italic;">
					Powered by <a href="http://www.chainsoft.co.th">Chainsoft Co., Ltd.</a>
				</span>
				<span style="clear:both;"></span>
			</div>
			<!-- Histats.com  START  (standard)
				<script type="text/javascript">document.write(unescape("%3Cscript src=%27http://s10.histats.com/js15.js%27 type=%27text/javascript%27%3E%3C/script%3E"));</script>
				<a href="http://www.histats.com" target="_blank" title="website statistics" >
					<script  type="text/javascript" >
						try {Histats.start(1,1699586,4,3023,130,80,"00011010");
						Histats.track_hits();} catch(err){};
					</script>
				</a>
				<noscript>
					<a href="http://www.histats.com" target="_blank"><img  src="http://sstatic1.histats.com/0.gif?1699586&101" alt="website statistics" border="0"></a>
				</noscript>
			 Histats.com  END  -->
		</div>
	</center>
</div>