<!-- <script type="text/javascript">$(document).snowfall({ flakeCount: 25 });</script> -->
<!-- <img class="header" src="/images/header.jpg" />  -->
<div class="header-content">
	<a href="/index" ><img src="/images/logo.png" width="240" height="100" style="vertical-align:middle;margin:12px 8px 0px 0px;"/></a>
	<!--embed src="/images/adver/TitanFull.swf" width="700" height="90" style="vertical-align:middle;margin:5px 10px 0px 0px;"></embed-->
        <a href="/support" ><img src="/images/adver/adv-2.png" width="700" height="90" style="vertical-align:middle;margin:5px 10px 0px 0px;"/></a>
	<div style="float:right;width:38px;margin-top:35px;">
		<?php if(Eaglet_Utils_Bilingual::isThaiLang()){ ?>
			<img src="/images/thai_select.png" style="margin-bottom:10px;"/>
			<a href="/user/changelang/lang//?referredUri=<?= rawurlencode($_SERVER['REQUEST_URI']);?>">
				<img src="/images/eng.png" />
			</a>
		<?php }
		else{ ?>
			<a href="/user/changelang/lang/1/?referredUri=<?= rawurlencode($_SERVER['REQUEST_URI']);?>">
				<img src="/images/thai.png" style="margin-bottom:10px;"/>
			</a>
			<img src="/images/eng_select.png" />
		<?php } ?>
	</div>
	<div style="clear:both;"></div>
</div>