<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="th" xml:lang="th">
<head>
  <link rel="shortcut icon" href="/images/logo_small.ico" />
  <!-- <link rel="icon" type="image/x-icon" href="/images/logo_small.ico" />  -->
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" >
  <?php echo $this->headMeta();?>
  <meta name="keywords" content="<?= $this->translate('LAYOUT_KEYWORD_TEXT'); ?>" />
  <meta name="description" content="<?= $this->translate('LAYOUT_DESCRIPTION_TEXT'); ?>" />
  <meta property="fb:app_id" content="282308108446651"/>
  <meta property="og:type" content="game"/>
  <meta property="og:image" content="http://lendota.com/images/logo_white.jpg"/>
  <meta name="stats-in-th" content="36f3" />
  <title>LenDotA.com | ข่าวสารการแข่งขันและรีเพล DotA และ DotA2</title>
  <?php 
  	echo $this->headLink()->prependStylesheet('/css/template.css?v=4')
  						  ->appendStylesheet('/css/menu/menu.css') 
  						  ->appendStylesheet('/resources/bracket/jquery.bracket-3.css')
  						  ->appendStylesheet('/css/store/cart.css')
  						  ->appendStylesheet('/css/jqueryui/jquery-ui.css')
  						  ->appendStylesheet('/css/flag.css')
  						  ->appendStylesheet('/css/jqueryui/jqClock.css'); 
  	echo $this->headScript()->prependFile('/resources/jquery/jquery-1.7.2.min.js')
  							->appendFile('/js/menu/menu.js')
  							->appendFile('/resources/bracket/jquery.bracket-3.js')
  							//->appendFile('/js/jqueryui/snowfall.min.jquery.js')
  							->appendFile('/js/jqueryui/jquery-ui.min.js')
  							->appendFile('/js/jqueryui/jquery-ui-timepicker-addon.js')
  							->appendFile('/js/jqueryui/jqClock.min.js');
  ?>
  <link rel="stylesheet" href="/css/handheld.css" media="only screen and (min-device-width: 320px) and (max-device-width: 961px)" />
<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="/css/custom-ie.css" />
<![endif]-->
<!--[if lt IE 9]>
	 <link rel="stylesheet" type="text/css" href="/css/custom-lt-ie9.css" />
<![endif]-->
<!--[if lte IE 7]>
	 <link rel="stylesheet" type="text/css" href="/css/custom-ie7.css" />
<![endif]-->
<!--[if IE 8]>
	 <link rel="stylesheet" type="text/css" href="/css/custom-ie8.css" />
<![endif]-->
<!--[if IE 9]>
	 <link rel="stylesheet" type="text/css" href="/css/custom-ie9.css" />
<![endif]-->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24346062-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</head>
<body>
	<a href="http://www.facebook.com/CMStormThai" target="_blank"><img src="/images/web/cmstorm_bg.jpg" class="bg"/></a>
	<div class="bodyCenter">
		<?php echo $this->render('header.phtml'); ?>
		<?php echo $this->render('nav.phtml'); ?>
		<?php echo $this->layout()->content; ?>
		<?php echo $this->render('footer.phtml'); ?>
	</div>
</body>
</html>