<h1 class="header">
	Access Clan
</h1>
<div class="divLeft">
	<div class="RoundBlack"> 
		<div style="padding:10px 20px 20px 20px;">
			<center>
				<div>
					<span style="color:#82BDFF;"><?php echo $this->usernameChieftain;?></span>
					<span style="padding:0px 5px 0px 5px;">ได้ชวนคุณเข้าแคลน</span>
				 	<span style="color:#82BDFF;"><?php echo $this->clanTag;?></span>
				</div>
				<div style="margin:15px 0px 15px 0px;">
					คุณจะตอบรับ หรือไม่?
				</div>
				<div>
					<input type="button" value="Yes" style="margin-right:30px;" onclick="window.location='/user/accessclan/agree/yes'"></input>
					<input type="button" value="No" onclick="window.location='/user/accessclan/agree/no'"></input>
				</div>
			</center>
		</div>
	</div>
</div>