<script>
	document.title = '<?=$this->translate('DOWNLOAD_FANART_TITLE'); ?>';
</script>
<link rel="stylesheet" href="/resources/css/lightbox.css" type="text/css" media="screen" />
<script src="/resources/js/AC_RunActiveContent.js" type="text/javascript"></script>
<script src="/resources/js/builder.js" type="text/javascript"></script>
<script src="/resources/js/prototype.js" type="text/javascript"></script>
<script src="/resources/js/scriptaculous.js?load=effects,builder" type="text/javascript"></script>
<script src="/resources/js/lightbox.js" type="text/javascript"></script>

<h1 class="header">
	DotA Fan Art
</h1>
<div style="width:750px;margin:0px auto;">
	<div style="height:388px;">
		<?php foreach ($this->fanartPaginator as $fanart):?>
			<a rel="lightbox[roadtrip]" href="/upload/fanart/<?php echo $fanart;?>" >
				<img src="/upload/fanart/<?php echo $fanart;?>" style="margin:10px 10px 10px 10px;" width="100" height="77" />
			</a>
		<?php endforeach;?>
		
	</div>
	<div style="margin-top:10px;">
		<?php 
			echo $this->paginationControl(
						$this->fanartPaginator,
	                    'Sliding',
	                    '/template/paging_nav.phtml'); 
		?>
	</div>
</div>
