<div class="sahBody">
	<p>
		The overall goal for this site is to provide a long term service to the DotA community improve a DotA player's ability to enjoy the game and become more immersed in the DotA world overall.
		<br>
		<br>
		I do not currently plan on having any advertisements on the site, so please do not send requests regarding this. Our focus is going to be on the well-being of the game and nourishing the community at large. Ad revenue or maximizing traffic will not be a driving force behind any decisions we make.
		<br>
		<br>
		7Dot.com will actively promote events and news from many different communities that support DotA. While we want to provide users with a quality experience here, our view is that the more we raise exposure to the positive activities that many leagues, fansites, and organizations are doing the better it is for DotA.
	</p>
</div>
